[package]
name = "opt-proto"
version = "0.1.0"
authors = ["William Brandon", "Wilson Berkow", "Frank Dai"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "1.1.0"
pretty = "0.5.2"
failure = "0.1.5"
im-rc = "12.3.3"
itertools = "0.8.0"
lazy_static = "1.3.0"

# RNG used for procedurally (but deterministically) generating test inputs
rand = "0.6.5"
rand_pcg = "0.1.1"
