[package]
name = "morphic"
version = "0.1.0"
authors = ["William Brandon", "Wilson Berkow", "Frank Dai", "Benjamin Driscoll"]
description = "Pure functional programming with whole-program memory management inference"
edition = "2018"
build = "build.rs"

[build-dependencies]
find_clang = { path = "./find_clang" }
lalrpop = "0.18.1"
walkdir = "2.3.1"

[dependencies]
find_clang = { path = "./find_clang" }
lalrpop-util = "0.18.1"
im-rc = "12.3.3"
itertools = "0.8.0"
lazy_static = "1.3.0"
stacker = "0.1.5"
better-panic = "0.2.0"
clap = { version = "2.33.0", features = ["color"] }
cc = "1.0.50"
tempfile = "3.1.0"
crossbeam-channel = "0.4.2"
inkwell = { git = "https://github.com/TheDan64/inkwell", rev = "41b9624", features = ["llvm10-0"] }
ansi_term = "0.12.1"
textwrap = "0.11.0"
json = "0.12.4" # used for string escaping in profile report generation

# Error handling
anyhow = "1.0.28"
thiserror = "1.0.15"

# RNG used for procedurally (but deterministically) generating test inputs
rand = "0.6.5"
rand_pcg = "0.1.1"

[workspace]
members = ["benchmark"]

[profile.dev.package.criterion]
opt-level = 3
