[package]
name = "opt-proto"
version = "0.1.0"
authors = ["William Brandon <hypercube97@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "1.1.0"
failure = "0.1.5"
